name: Release Builds - Windows 32 bit

on:
  workflow_dispatch:

jobs:
  release_win:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: "./"

      - name: Build and package
        run: |
          # Replace this with your build commands
          npm install
          npm run rename
          npm test
          node-gyp clean
          npm run rebuild_ia32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Windows 32-bit
          release_name: Release Windows 32-bit
          body: |
            This is the release for Windows 32-bit
          draft: false
          prerelease: false

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/node_printer.node
          asset_name: node_printer.node
          asset_content_type: application/octet-stream
